#!/usr/bin/env bash

if [ ! $(id -u) -eq 0 ]; then 
    echo -e "Must be ran as Root"; 
    exit 1 
fi

function Inject()
{
    [[ ! -z "$SUDO_USER" ]] && RUNUSER="$SUDO_USER" || RUNUSER="$LOGNAME"

    RUNCMD="sudo -u $RUNUSER"
    line=$(pgrep -u $RUNUSER -o hl2_linux)
    arr=($line)

    if [ $# == 1 ]; then
        proc=$1
    else
        if [ ${#line} == 0 ]; then
            echo -e "Team fortress 2 is not running"
            exit 1
        fi
        proc=${line}
    fi

    file="/tmp/.gl$(head /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 6)"; 
    cp "Build/lesshook.so" "$file";

    # [PORT] : [CALL VOID* CHAR] : DLOPEN : DLERROR     .gl                 \
    gdb -n -q -batch                                                        \
        -ex "attach $proc"                                                  \
        -ex "call ((void*(*)(const char*, int))dlopen)(\"$file\", 1)"       \
        -ex "call ((char*(*)(void))dlerror)()"                              \
        -ex "detach"                                                        \
        -ex "quit"

    rm $file
}

Inject